#!/usr/bin/bash

CONTAINER_NAME="aws-cli"
AWS_CLI_VERSION="2.4.18"

AWS_CONFIG_FILE=${AWS_CONFIG_FILE:-"$HOME/.aws/config"}
AWS_SHARED_CREDENTIALS_FILE=${AWS_SHARED_CREDENTIALS_FILE:-"$HOME/.aws/credentials"}

if [[ $(docker ps --format "{{.Names}}" --filter "name=${CONTAINER_NAME}" | wc -l) -eq 0 ]]; then
  docker run --name $CONTAINER_NAME -d -t \
    --entrypoint /bin/bash \
    --user "$(id -u):$(id -g)" \
    -e "AWS_CONFIG_FILE=/tmp/.aws/config" \
    -e "AWS_SHARED_CREDENTIALS_FILE=/tmp/.aws/credentials" \
    -v "$(pwd):/aws:ro" \
    -v "${AWS_CONFIG_FILE}:/tmp/.aws/config:rw" \
    -v "${AWS_SHARED_CREDENTIALS_FILE}:/tmp/.aws/credentials:rw" \
    amazon/aws-cli:${AWS_CLI_VERSION} > /dev/null

  if [ $? -ne 0 ]; then
    echo "Failed to start the AWS CLI container, try again"
    exit 1
  fi
fi

docker exec -ti $CONTAINER_NAME aws $@
